version: '3'

services:
  bind9:
    container_name: DNS-2
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
    networks:
      DNS-Network-1:
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./Configuration:/etc/bind
    restart: unless-stopped
networks:
  DNS-Network-1:
    name: DNS-Network-2
    driver: bridge
    driver_opts:
      parent: DNS-IF-2