version: '3'

services:
  bind9:
    container_name: DNS
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Australia/Canberra
    networks:
      steam-cache:
        ipv4_address: 172.30.0.69
    volumes:
      - ./Configuration:/etc/bind
    restart: always
networks:
  steam-cache:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24