version: '3'

services:
  bind9:
    container_name: DNS
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Australia/Canberra
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "127.0.0.1:53:53/tcp"
      # - "127.0.0.1:53:53/udp"
    volumes:
      - ./Configuration:/etc/bind
    restart: always
networks:
  steam-cache:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
