version: '3'

services:
  bind9:
    container_name: DNS-SERVER
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      default:
    volumes:
      - ./DNS/Configuration:/etc/bind
    restart: unless-stopped